pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    restore: true
    mount:
      - ./node_modules
      - ./package-lock.json
      - ./yarn.lock
    volumes:
      - /tmp/cache:/cache

  test:
    image: node:8-alpine
    when:
      event: 
        - pull_request
        - push
        - tag

    commands:
      - yarn
      - yarn test -- --coverage


  code-cov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - ./coverage/lcov.info


  rebuild-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    rebuild: true
    mount:
      - ./node_modules
      - ./package-lock.json
      - ./yarn.lock

    volumes:
      - /tmp/cache:/cache